[package]
name = "client_sdk_kotlin_codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
client_sdk_schema.workspace = true
client_sdk_utils.workspace = true
convert_case = { workspace = true }
